// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031014231_AddPaymentTransactionTable")]
    partial class AddPaymentTransactionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyApp.Data.Entities.GenerationHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InputImages")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("GenerationHistories");
                });

            modelBuilder.Entity("MyApp.Data.Entities.MembershipPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModelGenerationLimit")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageName");

                    b.ToTable("MembershipPackages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CreatedAt = new DateTime(2025, 10, 31, 1, 42, 31, 338, DateTimeKind.Utc).AddTicks(3071),
                            Description = "Gói dùng thử miễn phí với 5 lượt gen model 3D",
                            DurationDays = 7,
                            IsDeleted = false,
                            ModelGenerationLimit = 5,
                            PackageName = "Free Trial",
                            Price = 0m
                        },
                        new
                        {
                            PackageId = 2,
                            CreatedAt = new DateTime(2025, 10, 31, 1, 42, 31, 338, DateTimeKind.Utc).AddTicks(3076),
                            Description = "Gói cơ bản cho người dùng thông thường với 50 lượt gen/tháng",
                            DurationDays = 30,
                            IsDeleted = false,
                            ModelGenerationLimit = 50,
                            PackageName = "Basic",
                            Price = 99000m
                        },
                        new
                        {
                            PackageId = 3,
                            CreatedAt = new DateTime(2025, 10, 31, 1, 42, 31, 338, DateTimeKind.Utc).AddTicks(3078),
                            Description = "Gói cao cấp với 200 lượt gen/tháng và ưu tiên hỗ trợ",
                            DurationDays = 30,
                            IsDeleted = false,
                            ModelGenerationLimit = 200,
                            PackageName = "Premium",
                            Price = 299000m
                        },
                        new
                        {
                            PackageId = 4,
                            CreatedAt = new DateTime(2025, 10, 31, 1, 42, 31, 338, DateTimeKind.Utc).AddTicks(3079),
                            Description = "Gói chuyên nghiệp với số lượt gen không giới hạn",
                            DurationDays = 30,
                            IsDeleted = false,
                            ModelGenerationLimit = -1,
                            PackageName = "Pro",
                            Price = 499000m
                        });
                });

            modelBuilder.Entity("MyApp.Data.Entities.Model3D", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("MyApp.Data.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrTxId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TxnRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VnpayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("VnpayTransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PackageId");

                    b.HasIndex("TxnRef")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("MyApp.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyApp.Data.Entities.UserMembershipSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingGenerations")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalGenerationsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PackageId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "Status", "EndDate");

                    b.ToTable("UserMembershipSubscriptions");
                });

            modelBuilder.Entity("MyApp.Data.Entities.GenerationHistory", b =>
                {
                    b.HasOne("MyApp.Data.Entities.Model3D", "Model3D")
                        .WithMany("GenerationHistories")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Data.Entities.User", "User")
                        .WithMany("GenerationHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model3D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Data.Entities.Model3D", b =>
                {
                    b.HasOne("MyApp.Data.Entities.User", "User")
                        .WithMany("Models")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Data.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("MyApp.Data.Entities.MembershipPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Data.Entities.UserMembershipSubscription", b =>
                {
                    b.HasOne("MyApp.Data.Entities.MembershipPackage", "Package")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Data.Entities.User", "User")
                        .WithMany("MembershipSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Data.Entities.MembershipPackage", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("MyApp.Data.Entities.Model3D", b =>
                {
                    b.Navigation("GenerationHistories");
                });

            modelBuilder.Entity("MyApp.Data.Entities.User", b =>
                {
                    b.Navigation("GenerationHistories");

                    b.Navigation("MembershipSubscriptions");

                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
